In [1]:
import numpy as np
from scipy import stats
import pandas as pd

### 1. Buscad un conjunto de datos a analizar:  Se recomienda que el conjunto de datos tenga variables numéricas y categóricas, ya que también se analizarán.

Hemos escogido un archivo que contiene información sobre los 1000 influencers con más repercusión en RRSS:

In [2]:
df_influencers = pd.read_csv("../Estadistica/instagram_global_top_1000.csv")

In [3]:
df_influencers.head(5)

Country  Rank        Account              Title  \
0     All     1      cristiano  Cristiano Ronaldo   
1     All     2    kyliejenner            Kylie 🤍   
2     All     3       leomessi          Leo Messi   
3     All     4  kendalljenner            Kendall   
4     All     5    selenagomez       Selena Gomez   

                                       Link                   Category  \
0      https://www.instagram.com/cristiano/         Sports with a ball   
1    https://www.instagram.com/kyliejenner/    Fashion|Modeling|Beauty   
2       https://www.instagram.com/leomessi/  Sports with a ball|Family   
3  https://www.instagram.com/kendalljenner/           Modeling|Fashion   
4    https://www.instagram.com/selenagomez/            Music|Lifestyle   

     Followers Audience Country  Authentic engagement  Engagement avg  \
0  400100000.0            India             7800000.0       9500000.0   
1  308800000.0    United States             6200000.0      10100000.0   
2  306300000.0        Argentina             4800000.0       6500000.0   
3  217800000.0    United States             3400000.0       5400000.0   
4  295800000.0    United States             2700000.0       3600000.0   

                      Scraped  
0  2022-02-07 16:50:24.798803  
1  2022-02-07 16:50:24.798803  
2  2022-02-07 16:50:24.798803  
3  2022-02-07 16:50:24.798803  
4  2022-02-07 16:50:24.798803

Comprobamos que el conjunto de datos tenga variables numéricas y categóricas:

In [5]:
df_influencers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Country               1000 non-null   object 
 1   Rank                  1000 non-null   int64  
 2   Account               1000 non-null   object 
 3   Title                 983 non-null    object 
 4   Link                  1000 non-null   object 
 5   Category              909 non-null    object 
 6   Followers             1000 non-null   float64
 7   Audience Country      993 non-null    object 
 8   Authentic engagement  1000 non-null   float64
 9   Engagement avg        1000 non-null   float64
 10  Scraped               1000 non-null   object 
dtypes: float64(3), int64(1), object(7)
memory usage: 86.1+ KB


In [6]:
df_influencers.columns

Index(['Country', 'Rank', 'Account', 'Title', 'Link', 'Category', 'Followers',
       'Audience Country', 'Authentic engagement', 'Engagement avg',
       'Scraped'],
      dtype='object')

In [7]:
df_influencers.isnull().sum()

Country                  0
Rank                     0
Account                  0
Title                   17
Link                     0
Category                91
Followers                0
Audience Country         7
Authentic engagement     0
Engagement avg           0
Scraped                  0
dtype: int64

### 2. Extraed los siguentes estadísticos del conjunto de datos para varias de las variables disponibles:

Vamos a extraer los valores estadísticos de la variable "Followers" y de "Authentic engagement", que hacen referencia al número de seguidores y al nivel de implicación de los mismos respectivamente.

* Media

In [8]:
media_followers = df_influencers["Followers"].mean()
media_followers

24836100.0

In [9]:
print("Cada influencer tiene una media de", media_followers,"seguidores.")

Cada influencer tiene una media de 24836100.0 seguidores.


In [10]:
media_engagement = df_influencers["Authentic engagement"].mean()
media_engagement

649122.8

In [11]:
print("Una media de", media_engagement," seguidores, son interactivos con los influercers a los que siguen.")

Una media de 649122.8  seguidores, son interactivos con los influercers a los que siguen.


* Desviación con respecto de la media

Este estadístico nos permitirá calcular cuanto difiere cada valor respecto a su media aritmética.

In [12]:
desviacion_followers = df_influencers["Followers"] - media_followers
desviacion_followers

0      375263900.0
1      283963900.0
2      281463900.0
3      192963900.0
4      270963900.0
          ...     
995    -17136100.0
996    -13336100.0
997    -14736100.0
998    -11136100.0
999    -18636100.0
Name: Followers, Length: 1000, dtype: float64

In [13]:
desviacion_engagement = df_influencers["Authentic engagement"] - media_engagement
desviacion_engagement

0      7150877.2
1      5550877.2
2      4150877.2
3      2750877.2
4      2050877.2
         ...    
995    -402522.8
996    -502622.8
997    -472622.8
998    -502722.8
999    -343522.8
Name: Authentic engagement, Length: 1000, dtype: float64

* Varianza

In [4]:
varianza_followers = df_influencers["Followers"].var()
varianza_followers

1499349496286270.5

In [5]:
varianza_engagement = round(df_influencers["Authentic engagement"].var(),2)
varianza_engagement

1207369145805.94

In [12]:
print(f"Los datos de la variable Followers tienen una varianza de",varianza_followers, "y Authentic engagement de", varianza_engagement)

Los datos de la variable Followers tienen una varianza de 1499349496286270.5 y Authentic engagement de 1207369145805.94


* Desviación típica

In [14]:
dt_followers = round(df_influencers["Followers"].std(),2)
dt_followers

38721434.58

In [15]:
dt_engagement = round(df_influencers["Authentic engagement"].std(),2)
dt_engagement

1098803.51

In [18]:
print(f"Con estos cálculos, podemos saber que la desviación de los valores de Followers con respecto a su media es de", dt_followers, ", y la de Authentic engagement de", dt_engagement)

Con estos cálculos, podemos saber que la desviación de los valores de Followers con respecto a su media es de 38721434.58 , y la de Authentic engagement de 1098803.51


* Moda

In [19]:
moda_fol = df_influencers["Followers"].mode()[0]
moda_fol

7800000.0

In [20]:
moda_eng = df_influencers["Authentic engagement"].mode()[0]
moda_eng

1100000.0

In [22]:
print(f"El valor que más se repite en la columna Followers es ", moda_fol, ", y en la de Authentic engagement ", moda_eng)

El valor que más se repite en la columna Followers es  7800000.0 , y en la de Authentic engagement  1100000.0


* Mediana

In [23]:
median_fol = df_influencers["Followers"].median()
median_fol

14400000.0

In [24]:
median_eng = df_influencers["Authentic engagement"].median()
median_eng

363700.0

In [25]:
print(f"El valor que ocupa el lugar central en la lista Followers es ", median_fol, ", y en Authentic engagement ", median_eng)

El valor que ocupa el lugar central en la lista Followers es  14400000.0 , y en Authentic engagement  363700.0


* Media Ponderada

La media ponderada parte de la base de que no todos los datos tienen la misma importancia, de manera que se multiplica cada uno de ellos por un valor antes de sumarlos.

De manera aleatoria vamos a darle pesos a nuestro datos, para ello vamos a crear un array:

In [22]:
w = np.random.randint(1,100, df_influencers.shape[0])

Ya tenemos nuestro parámetro "weights", lo utilizaremos en el método "average" para calcular la media ponderada:

In [23]:
avg_fol = round(np.average(df_influencers["Followers"],weights=w),2)
avg_fol

25126013.59

In [24]:
avg_eng = round(np.average(df_influencers["Authentic engagement"],weights=w),2)
avg_eng

642687.23

* Robustez

La robustez determina por así decir la vulnerabilidad de un conjunto de datos, si es lo suficientemente representativa como para no verse alterada si hubiera un valor extremadamente alto o bajo (outliers).
Sabemos que la media y la mediana no presentan la misma robustez, y que las alteraciones en los datos les afectan de manera distinta.

In [73]:
media_fol= df_influencers["Followers"].mean()
media_fol

24836100.0

In [74]:
median_fol = df_influencers["Followers"].median()
median_fol

14400000.0

In [75]:
#En una copia del dataset, vamos a hacer una modificación para comprobar en qué medida se ven 
# alterados ambos estadísticos:
df_influencers2 = df_influencers.copy()

In [76]:
df_influencers2["Followers"][1]= df_influencers2["Followers"][1]*100

/tmp/ipykernel_5085/4011228309.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_influencers2["Followers"][1]= df_influencers2["Followers"][1]*100


In [77]:
df_influencers2["Followers"].mean()

55407300.0

In [78]:
df_influencers2["Followers"].median()

14400000.0

Al cambiar esos datos vemos como la media ha pasado de 24836100.0 a 55407300.0, mientras la mediana se ha mantenido en 14400000.0
Esto se debe a que la media es un valor muy poco robusto (ha cambiado mucho con sólo una variación), y la mediana presenta sin embargo mucha robustez.

Es preciso conocer el punto de ruptura, es una medida de robustez que nos informará de la fracción de datos que podría recibir valores inusuales sin que el estadístico en cuestión se viera tan alterado que dejara de ser útil.

In [26]:
punto_de_ruptura = 1/1000
punto_de_rupturaprint(f"El valor que más se repite en la columna Followers es ", moda_fol, ", y en la de Authentic engagement ", moda_eng)

0.001

En nuestro caso tenemos 1000 registros y eso nos proporciona un punto de ruptura muy bajo.
A priori cuanto más bajo es el punto de ruptura más robusta sería la media, pero hay que tener en cuenta que la robustez por sí sola no es suficiente, hay que considerar otros estadísticos, como por ejemplo la desviación estándar o si por ejemplo dentro de nuestros datos encontramos outliers, si hay datos muy dispersos la media no será representativa de la población, ya que un valor estadístico por si solo podría estar sesgado.

* Coeficiente de variación

In [29]:
coef_var_fol = media_followers / dt_followers
coef_var_fol

0.0006414044383786362

In [30]:
coef_var_eng = media_engagement / dt_engagement
coef_var_eng

0.0005907542104593387

En ambos casos el coeficiente de variación es muy bajo, esto podría hacer pensar (si sólo se tuviera en cuenta este estadístico) que el conjunto de datos es homogéneo y que no hay valores que se separen demasiado de la media. Habrá que tener en cuenta, al igual que hemos comentado al estudiar la robustez, si hubiera muchos valores atípicos.